print ("Wecome to CT8!")
name = input("what is your name?")
print ("Im so exited to talk to you today!")
print(f"hello {name} welcome to the chat box")
myclass= input("what class are you in today")
print(f"well im glad to hear that {myclass} is happing for you this year!")
Class1= input("what other classes are you exited for?!")
print (f"{Class1} seems fun!")
feeling = input ("how are you feeling about school this year!") 
print (f"well even though you feel {feeling}")
